// City configuration — the single edit surface for running this engine for
// a different city. Every city-specific value the code consumes lives here;
// see docs/city-template.md for the full field reference.
//
// Generated by `npm run init-city`. Edit freely — the geographic boxes in
// particular are derived defaults worth hand-tuning to your metro's shape.
//
// Import rules (enforced by convention, see docs/city-template.md):
//   - Node build code imports the validated `CITY` from lib/config/city.ts.
//   - Web code (and the web-reachable lib/config/tags.ts) imports THIS file
//     directly, so Zod never lands in the browser bundle.
//
// The `satisfies` check below gives immediate editor feedback; full Zod
// validation (including cross-field bounds checks) runs at build startup.
import type { CityConfig } from "./lib/config/city.js";

const cityConfig = {
    city: {
        // Display name, used in web UI copy and as the Ticketmaster
        // venue-address fallback city.
        name: "Houston",
        // Two-letter state/region code (Ticketmaster address fallback).
        state: "TX",
        // IANA timezone for the city — the default for new sources.
        timezone: "America/Chicago",
    },
    site: {
        // Site/brand name: <title>, PWA manifest, llms.txt, web PRODID.
        name: "832.events",
        // <meta name="description"> for the web UI.
        description:
            "Browse event calendars from Houston venues, neighborhoods, and organizations. Subscribe via ICS, add events to Google Calendar, or follow RSS feeds for music, art, markets, community events, and more.",
        // Deployed site origin with trailing slash. Used as the base for
        // RSS/sitemap URLs. The SITE_BASE_URL env var still takes precedence.
        baseUrl: "https://832.events/",
        // Deployed site origin without trailing slash, used for the
        // deployed-site manifest probe (new-source detection) and report
        // fetches. The PRODUCTION_URL env var still takes precedence.
        productionUrl: "https://832.events",
        // GitHub owner/repo of this copy — llms.txt source links and the
        // web feedback fallback link.
        repo: "crowecawcaw/832events",
        // Short mark shown in the boot splash and loading screen.
        bootLogoText: "832",
    },
    ics: {
        // PRODID identifier stamped into every generated ICS file.
        prodId: "832.events",
    },
    geocoder: {
        // Nominatim usage policy requires an identifying User-Agent:
        // https://operations.osmfoundation.org/policies/nominatim/
        nominatimUserAgent: "832.events/1.0 (https://832.events)",
        // Tight box around the metro, sent as `viewbox=…&bounded=1` so
        // ambiguous venue names resolve to the local instance.
        nominatimViewbox: { west: -96.0, south: 29.3, east: -94.8, north: 30.25 },
    },
    map: {
        // Default map view (city center).
        center: { lat: 29.7604, lng: -95.3698 },
        defaultZoom: 11,
        // Populated metro extent used to reject distant outliers from the
        // default map fit. Derived from the city center — tune to your
        // metro/county shape.
        clampBounds: { south: 29.45, west: -95.85, north: 30.1, east: -94.95 },
    },
    // Generous regional bounding box for CI sanity checks on venue
    // coordinates (a venue outside this box is a geocoding bug).
    venueSanityBbox: { latMin: 27.5104, latMax: 32.0104, lngMin: -98.1198, lngMax: -92.6198 },
    // Neighborhood tags — drives TAG_CATEGORIES['Neighborhoods'] in
    // lib/config/tags.ts (website sidebar grouping + neighborhood filters).
    // Grows over time as sources tag new neighborhoods.
    neighborhoods: [
        "Downtown",
        "Midtown",
        "Montrose",
        "The Heights",
        "Museum District",
        "EaDo",
        "Rice Village",
        "Washington Ave",
        "River Oaks",
        "Uptown",
        "Medical Center",
        "Third Ward",
        "Second Ward",
        "Memorial",
        "Energy Corridor",
        "Spring Branch",
        "Bellaire",
        "West University",
        "Sharpstown",
        "Garden Oaks",
        "Wedgewood",
        "Upper Kirby",
        "Near Northside",
        "Clear Lake",
    ],
    // GoatCounter analytics. Set to null to disable analytics entirely
    // (no snippet is injected into index.html).
    analytics: null as { goatcounterCode: string } | null,
} satisfies CityConfig;

export default cityConfig;
